name: torrent_diff_tool
description: "A new Flutter project."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.8
  dtorrent_parser: ^1.0.9
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.4
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
